USE [master]
GO

/****** Object:  Database [ETrade]    Script Date: 31/01/2021 1:44:52 PM ******/
CREATE DATABASE [ETrade]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ETrade', FILENAME = N'C:\Users\fatih\ETrade.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ETrade_log', FILENAME = N'C:\Users\fatih\ETrade_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ETrade].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ETrade] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ETrade] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ETrade] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ETrade] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ETrade] SET ARITHABORT OFF 
GO

ALTER DATABASE [ETrade] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [ETrade] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ETrade] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ETrade] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ETrade] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ETrade] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ETrade] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ETrade] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ETrade] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ETrade] SET  ENABLE_BROKER 
GO

ALTER DATABASE [ETrade] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ETrade] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ETrade] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ETrade] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ETrade] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ETrade] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [ETrade] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ETrade] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ETrade] SET  MULTI_USER 
GO

ALTER DATABASE [ETrade] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ETrade] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ETrade] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ETrade] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ETrade] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ETrade] SET QUERY_STORE = OFF
GO

USE [ETrade]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [ETrade] SET  READ_WRITE 
GO

